export const categories = [
  { id: "all", name: "All" },
  { id: "appetizers", name: "Appetizers" },
  { id: "biryani", name: "Biryani & Rice" },
  { id: "curry", name: "Curries" },
  { id: "tandoori", name: "Tandoori" },
  { id: "desserts", name: "Desserts" },
  { id: "beverages", name: "Beverages" },
];

export const menuItems = [
  {
    id: 1,
    category: "appetizers",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas, served with mint chutney.",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.7,
  },
  {
    id: 2,
    category: "appetizers",
    name: "Chicken Pakora",
    description: "Tender chicken pieces coated in spiced batter and deep fried until golden.",
    price: 9.99,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=400&auto=format&fit=crop",
    isSpicy: true,
    isVegetarian: false,
    rating: 4.8,
  },
  {
    id: 3,
    category: "biryani",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice layered with tender chicken, aromatic spices, and saffron.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=400&auto=format&fit=crop",
    isSpicy: true,
    isVegetarian: false,
    rating: 4.9,
    isFeatured: true,
  },
  {
    id: 4,
    category: "biryani",
    name: "Mutton Biryani",
    description: "Premium mutton slow-cooked with aged basmati rice and traditional spices.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=400&auto=format&fit=crop",
    isSpicy: true,
    isVegetarian: false,
    rating: 4.9,
  },
  {
    id: 5,
    category: "biryani",
    name: "Vegetable Biryani",
    description: "Mixed vegetables and paneer cooked with aromatic basmati rice.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.6,
  },
  {
    id: 6,
    category: "curry",
    name: "Lamb Karahi",
    description: "Succulent lamb cooked in a wok with tomatoes, ginger, and green chilies.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1545247181-516773cae754?q=80&w=400&auto=format&fit=crop",
    isSpicy: true,
    isVegetarian: false,
    rating: 4.8,
    isFeatured: true,
  },
  {
    id: 7,
    category: "curry",
    name: "Butter Chicken",
    description: "Tender chicken in a rich, creamy tomato sauce with aromatic spices.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: false,
    rating: 4.7,
  },
  {
    id: 8,
    category: "curry",
    name: "Palak Paneer",
    description: "Cottage cheese cubes in a creamy spinach sauce with Indian spices.",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1618449840665-9ed506d73a34?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.6,
  },
  {
    id: 9,
    category: "tandoori",
    name: "Seekh Kebab",
    description: "Minced lamb skewers seasoned with herbs and spices, grilled to perfection.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=400&auto=format&fit=crop",
    isSpicy: true,
    isVegetarian: false,
    rating: 4.7,
  },
  {
    id: 10,
    category: "tandoori",
    name: "Chicken Tikka",
    description: "Boneless chicken marinated in yogurt and spices, cooked in tandoor.",
    price: 17.99,
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?q=80&w=400&auto=format&fit=crop",
    isSpicy: true,
    isVegetarian: false,
    rating: 4.8,
  },
  {
    id: 11,
    category: "tandoori",
    name: "Paneer Tikka",
    description: "Marinated cottage cheese cubes grilled with bell peppers and onions.",
    price: 14.99,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.6,
  },
  {
    id: 12,
    category: "desserts",
    name: "Gulab Jamun",
    description: "Deep-fried milk dumplings soaked in rose-flavored sugar syrup.",
    price: 5.99,
    image: "/images/gulab-jamun.png",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.9,
  },
  {
    id: 13,
    category: "desserts",
    name: "Kheer",
    description: "Creamy rice pudding with cardamom, nuts, and rose water.",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.7,
  },
  {
    id: 14,
    category: "beverages",
    name: "Mango Lassi",
    description: "Refreshing yogurt drink blended with sweet mango pulp.",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.8,
  },
  {
    id: 15,
    category: "beverages",
    name: "Masala Chai",
    description: "Traditional spiced tea with milk and aromatic spices.",
    price: 3.99,
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?q=80&w=400&auto=format&fit=crop",
    isSpicy: false,
    isVegetarian: true,
    rating: 4.9,
  },
];

export const restaurantInfo = {
  name: "Pak Cuisine",
  address: "123 Spice Street, Flavor District, New York, NY 10001",
  phone: "(123) 456-7890",
  email: "info@pakcuisine.com",
  openingHours: [
    { day: "Monday - Thursday", hours: "11:00 AM - 10:00 PM" },
    { day: "Friday - Saturday", hours: "11:00 AM - 11:00 PM" },
    { day: "Sunday", hours: "12:00 PM - 9:00 PM" },
  ],
  halal: "100% Halal Certified",
  faqs: [
    {
      question: "Is your food halal?",
      answer: "Yes, all our meat is 100% halal certified. We take great care to ensure our ingredients meet halal standards.",
    },
    {
      question: "Do you accommodate dietary restrictions?",
      answer: "Absolutely! We offer vegetarian, vegan, and gluten-free options. Our menu clearly marks dishes with dietary icons.",
    },
    {
      question: "Do I need a reservation?",
      answer: "While walk-ins are welcome, we highly recommend making a reservation, especially for weekends.",
    },
  ]
};
